apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-ip-pool"
spec:
  blocks:
  - cidr: "10.70.0.0/20"
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.name": "cilium-ingress"

